language: objective-c
osx_image: xcode9.1
branches:
  only:
    - master

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild test -enableCodeCoverage YES -workspace Example/ConfigurationProvider.xcworkspace -scheme ConfigurationProvider-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  - pod lib lint