#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: ConfigurationProvider
#==================================================================================================

settings:
  MARKETING_VERSION: "2.2.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "12.4"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "10.1"

configs:
  Debug: debug
  Release: release

#==================================================================================================
targets:
#==================================================================================================

#____________________________________________________________
# Framework

  ConfigurationProvider:

    platform: iOS
    type: framework

    sources:
      - path: ConfigurationProvider
      
    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PRODUCT_BUNDLE_IDENTIFIER: br.com.mobile.ConfigurationProvider
      INFOPLIST_FILE: ConfigurationProvider/Info.plist

      ENABLE_BITCODE: "NO"
      TARGETED_DEVICE_FAMILY: "1"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

#____________________________________________________________
# Tests

  ConfigurationProviderTests:

    platform: iOS
    type: bundle.unit-test

    sources:
      - path: ConfigurationProviderTests

    dependencies:
      - target: ConfigurationProvider

#==================================================================================================
schemes:
#==================================================================================================

  ConfigurationProviderSDK:
    build:
      targets:
        ConfigurationProvider: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ConfigurationProvider
      targets:
        - ConfigurationProviderTests

#==================================================================================================
